server:
  port: 8080
  servlet:
    context-path: /hotel

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/hotel_db"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
#      //ddl-auto = update thì khi đổi tên trong Entity sẽ bị tạo thêm column mới
    show-sql: true